Issue #1790: Adds tldextract cache update on docker build, fixes import error in main.py
(cherry picked from commit b0a7f8479afd74a7eee944ce8fed3b1d5efd52c7)

Co-authored-by: Federico Rossi <federico.rossi@smc.it>

diff --git a/connectors/openk9-crawler/connector/Dockerfile b/connectors/openk9-crawler/connector/Dockerfile
--- a/connectors/openk9-crawler/connector/Dockerfile
+++ b/connectors/openk9-crawler/connector/Dockerfile
@@ -28,6 +28,9 @@ COPY install_playwright.sh /etc/install_playwright.sh
 COPY wait_for_scrapyd.sh /app/wait_for_scrapyd.sh
 COPY scrapyd.conf /etc/scrapyd/scrapyd.conf
 
+# updates tldextract cache
+RUN tldextract --update || echo "Update failed, using local cached version"
+
 # Convert line endings and set permissions
 RUN dos2unix /etc/install_playwright.sh /app/wait_for_scrapyd.sh /etc/docker-entrypoint.sh && \
     chmod +x /etc/install_playwright.sh /app/wait_for_scrapyd.sh /etc/docker-entrypoint.sh && \
